name: smart_care
description: this application will help patients to consult any near or available doctor, analyze their state, etc...

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  fluttertoast: ^8.2.1
  http: ^0.13.5
  url_launcher: ^6.1.10
  flutter_animate: ^4.1.0
  font_awesome_flutter: ^10.4.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  google_fonts: ^4.0.3
  lottie: ^2.2.0
  fl_chart: ^0.61.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.14
  flutter_native_splash: ^2.2.18
  otp_text_field: ^1.1.3
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  sqflite: ^2.2.5
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  google_sign_in: ^6.0.1
  flutter_launcher_icons: ^0.12.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.1
  file_picker: ^5.2.5
  flutter_chat_ui: ^1.6.6
  mime: ^1.0.4
  open_filex: ^4.3.2
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  flutter_card_swiper: ^2.0.1
  animated_text_kit: ^4.2.2
  assets_audio_player: ^3.0.6
  flutter_chat_bubble: ^2.0.2
  flutter_keyboard_visibility: ^5.4.0
  day_night_time_picker: ^1.2.0+2
  comment_tree: ^0.3.0
  get_time_ago: ^1.1.8
  pdf: ^3.9.0
  path_provider: ^2.0.14
  firebase_messaging: ^14.4.0
  awesome_notifications: ^0.7.4+1
  intl_phone_field: ^3.1.0
  intl: ^0.17.0
  adaptive_theme: ^3.2.1
  camera: ^0.10.5
  syncfusion_flutter_calendar: ^21.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/icon/health.png
  color: "#00191A"
  android: true
  ios: true
  adaptive_icon_background: "assets/icon/health.png"
  adaptive_icon_foreground: "assets/icon/health.png"

flutter_icons:
  image_path: assets/icon/health.png
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/primaly_prevention/
    - assets/lottie/
    - assets/icon/
    - assets/audio/
    - assets/files/